# https://github.com/elastic/kibana-docker
FROM olinicola/filebeat

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>

COPY ./conf/filebeat.yml /etc/filebeat/filebeat.yml
