version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    expose:
      - "5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    # nginx容器挂载在与web容器相同的容器卷上
    volumes_from:
      - kibana
    links:
      - kibana:kibana
    networks:
      - elk
    volumes:
      - ./data/elk_nginx/log:/var/log/nginx


networks:

  elk:
    driver: bridge
